fragment ArticleParts on Article {
  __typename
  title
  date
  author
  type
  tags
  keywords
  summary
  image
  audio
  body
}

fragment SystematicTheologyParts on SystematicTheology {
  __typename
  title
  date
  author
  tags
  keywords
  summary
  image
  audio
  body
}

fragment ReformedTheologyParts on ReformedTheology {
  __typename
  title
  date
  author
  tags
  keywords
  summary
  image
  audio
  body
}
