fragment ArticleParts on Article {
  __typename
  title
  date
  author
  type
  tags
  keywords
  summary
  image
  audio
  body
}

fragment SystematicTheologyParts on SystematicTheology {
  __typename
  title
  subsection
  subsectionFolder
  order
  date
  body
}

fragment ReformedTheologyParts on ReformedTheology {
  __typename
  title
  subsection
  subsectionFolder
  order
  date
  body
}

fragment ChurchHistoryParts on ChurchHistory {
  __typename
  title
  subsection
  subsectionFolder
  group
  groupFolder
  order
  date
  body
}

fragment BookParts on Book {
  __typename
  title
  bookFolder
  date
  author
  keywords
  summary
  credits
  image
}

fragment BookChapterParts on BookChapter {
  __typename
  title
  bookFolder
  section
  sectionFolder
  order
  date
  body
}
