fragment ArticleParts on Article {
  __typename
  title
  date
  author
  type
  tags
  keywords
  summary
  image
  audio
  body
}

fragment SystematicTheologyParts on SystematicTheology {
  __typename
  title
  subsection
  subsectionFolder
  order
  date
  body
}

fragment ReformedTheologyParts on ReformedTheology {
  __typename
  title
  subsection
  subsectionFolder
  order
  date
  body
}
