//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  article: Article;
  articleConnection: ArticleConnection;
  systematicTheology: SystematicTheology;
  systematicTheologyConnection: SystematicTheologyConnection;
  reformedTheology: ReformedTheology;
  reformedTheologyConnection: ReformedTheologyConnection;
  churchHistory: ChurchHistory;
  churchHistoryConnection: ChurchHistoryConnection;
  book: Book;
  bookConnection: BookConnection;
  bookChapter: BookChapter;
  bookChapterConnection: BookChapterConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticleFilter>;
};


export type QuerySystematicTheologyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySystematicTheologyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SystematicTheologyFilter>;
};


export type QueryReformedTheologyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReformedTheologyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReformedTheologyFilter>;
};


export type QueryChurchHistoryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryChurchHistoryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ChurchHistoryFilter>;
};


export type QueryBookArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
};


export type QueryBookChapterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookChapterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookChapterFilter>;
};

export type DocumentFilter = {
  article?: InputMaybe<ArticleFilter>;
  systematicTheology?: InputMaybe<SystematicTheologyFilter>;
  reformedTheology?: InputMaybe<ReformedTheologyFilter>;
  churchHistory?: InputMaybe<ChurchHistoryFilter>;
  book?: InputMaybe<BookFilter>;
  bookChapter?: InputMaybe<BookChapterFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Article | SystematicTheology | ReformedTheology | ChurchHistory | Book | BookChapter | Folder;

export type Article = Node & Document & {
  __typename?: 'Article';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  author: Scalars['String']['output'];
  type: Scalars['String']['output'];
  tags: Array<Scalars['String']['output']>;
  keywords: Array<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  audio?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArticleFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  audio?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArticleConnectionEdges = {
  __typename?: 'ArticleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Article>;
};

export type ArticleConnection = Connection & {
  __typename?: 'ArticleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArticleConnectionEdges>>>;
};

export type SystematicTheology = Node & Document & {
  __typename?: 'SystematicTheology';
  title: Scalars['String']['output'];
  subsection: Scalars['String']['output'];
  subsectionFolder?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  date: Scalars['String']['output'];
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type SystematicTheologyFilter = {
  title?: InputMaybe<StringFilter>;
  subsection?: InputMaybe<StringFilter>;
  subsectionFolder?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SystematicTheologyConnectionEdges = {
  __typename?: 'SystematicTheologyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SystematicTheology>;
};

export type SystematicTheologyConnection = Connection & {
  __typename?: 'SystematicTheologyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SystematicTheologyConnectionEdges>>>;
};

export type ReformedTheology = Node & Document & {
  __typename?: 'ReformedTheology';
  title: Scalars['String']['output'];
  subsection: Scalars['String']['output'];
  subsectionFolder?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  date: Scalars['String']['output'];
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ReformedTheologyFilter = {
  title?: InputMaybe<StringFilter>;
  subsection?: InputMaybe<StringFilter>;
  subsectionFolder?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ReformedTheologyConnectionEdges = {
  __typename?: 'ReformedTheologyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ReformedTheology>;
};

export type ReformedTheologyConnection = Connection & {
  __typename?: 'ReformedTheologyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReformedTheologyConnectionEdges>>>;
};

export type ChurchHistory = Node & Document & {
  __typename?: 'ChurchHistory';
  title: Scalars['String']['output'];
  subsection: Scalars['String']['output'];
  subsectionFolder?: Maybe<Scalars['String']['output']>;
  group?: Maybe<Scalars['String']['output']>;
  groupFolder?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  date: Scalars['String']['output'];
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ChurchHistoryFilter = {
  title?: InputMaybe<StringFilter>;
  subsection?: InputMaybe<StringFilter>;
  subsectionFolder?: InputMaybe<StringFilter>;
  group?: InputMaybe<StringFilter>;
  groupFolder?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ChurchHistoryConnectionEdges = {
  __typename?: 'ChurchHistoryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ChurchHistory>;
};

export type ChurchHistoryConnection = Connection & {
  __typename?: 'ChurchHistoryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ChurchHistoryConnectionEdges>>>;
};

export type Book = Node & Document & {
  __typename?: 'Book';
  title: Scalars['String']['output'];
  bookFolder?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  author: Scalars['String']['output'];
  keywords: Array<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  credits?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BookFilter = {
  title?: InputMaybe<StringFilter>;
  bookFolder?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  credits?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type BookConnectionEdges = {
  __typename?: 'BookConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Book>;
};

export type BookConnection = Connection & {
  __typename?: 'BookConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookConnectionEdges>>>;
};

export type BookChapter = Node & Document & {
  __typename?: 'BookChapter';
  title: Scalars['String']['output'];
  bookFolder: Scalars['String']['output'];
  section?: Maybe<Scalars['String']['output']>;
  sectionFolder?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  date: Scalars['String']['output'];
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BookChapterFilter = {
  title?: InputMaybe<StringFilter>;
  bookFolder?: InputMaybe<StringFilter>;
  section?: InputMaybe<StringFilter>;
  sectionFolder?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BookChapterConnectionEdges = {
  __typename?: 'BookChapterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<BookChapter>;
};

export type BookChapterConnection = Connection & {
  __typename?: 'BookChapterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookChapterConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateArticle: Article;
  createArticle: Article;
  updateSystematicTheology: SystematicTheology;
  createSystematicTheology: SystematicTheology;
  updateReformedTheology: ReformedTheology;
  createReformedTheology: ReformedTheology;
  updateChurchHistory: ChurchHistory;
  createChurchHistory: ChurchHistory;
  updateBook: Book;
  createBook: Book;
  updateBookChapter: BookChapter;
  createBookChapter: BookChapter;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateArticleArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticleMutation;
};


export type MutationCreateArticleArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticleMutation;
};


export type MutationUpdateSystematicTheologyArgs = {
  relativePath: Scalars['String']['input'];
  params: SystematicTheologyMutation;
};


export type MutationCreateSystematicTheologyArgs = {
  relativePath: Scalars['String']['input'];
  params: SystematicTheologyMutation;
};


export type MutationUpdateReformedTheologyArgs = {
  relativePath: Scalars['String']['input'];
  params: ReformedTheologyMutation;
};


export type MutationCreateReformedTheologyArgs = {
  relativePath: Scalars['String']['input'];
  params: ReformedTheologyMutation;
};


export type MutationUpdateChurchHistoryArgs = {
  relativePath: Scalars['String']['input'];
  params: ChurchHistoryMutation;
};


export type MutationCreateChurchHistoryArgs = {
  relativePath: Scalars['String']['input'];
  params: ChurchHistoryMutation;
};


export type MutationUpdateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationCreateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationUpdateBookChapterArgs = {
  relativePath: Scalars['String']['input'];
  params: BookChapterMutation;
};


export type MutationCreateBookChapterArgs = {
  relativePath: Scalars['String']['input'];
  params: BookChapterMutation;
};

export type DocumentUpdateMutation = {
  article?: InputMaybe<ArticleMutation>;
  systematicTheology?: InputMaybe<SystematicTheologyMutation>;
  reformedTheology?: InputMaybe<ReformedTheologyMutation>;
  churchHistory?: InputMaybe<ChurchHistoryMutation>;
  book?: InputMaybe<BookMutation>;
  bookChapter?: InputMaybe<BookChapterMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  article?: InputMaybe<ArticleMutation>;
  systematicTheology?: InputMaybe<SystematicTheologyMutation>;
  reformedTheology?: InputMaybe<ReformedTheologyMutation>;
  churchHistory?: InputMaybe<ChurchHistoryMutation>;
  book?: InputMaybe<BookMutation>;
  bookChapter?: InputMaybe<BookChapterMutation>;
};

export type ArticleMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  summary?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  audio?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SystematicTheologyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subsection?: InputMaybe<Scalars['String']['input']>;
  subsectionFolder?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ReformedTheologyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subsection?: InputMaybe<Scalars['String']['input']>;
  subsectionFolder?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ChurchHistoryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subsection?: InputMaybe<Scalars['String']['input']>;
  subsectionFolder?: InputMaybe<Scalars['String']['input']>;
  group?: InputMaybe<Scalars['String']['input']>;
  groupFolder?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BookMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  bookFolder?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  summary?: InputMaybe<Scalars['String']['input']>;
  credits?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type BookChapterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  bookFolder?: InputMaybe<Scalars['String']['input']>;
  section?: InputMaybe<Scalars['String']['input']>;
  sectionFolder?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArticlePartsFragment = { __typename: 'Article', title: string, date: string, author: string, type: string, tags: Array<string>, keywords: Array<string>, summary?: string | null, image?: string | null, audio?: string | null, body: any };

export type SystematicTheologyPartsFragment = { __typename: 'SystematicTheology', title: string, subsection: string, subsectionFolder?: string | null, order?: number | null, date: string, body: any };

export type ReformedTheologyPartsFragment = { __typename: 'ReformedTheology', title: string, subsection: string, subsectionFolder?: string | null, order?: number | null, date: string, body: any };

export type ChurchHistoryPartsFragment = { __typename: 'ChurchHistory', title: string, subsection: string, subsectionFolder?: string | null, group?: string | null, groupFolder?: string | null, order?: number | null, date: string, body: any };

export type BookPartsFragment = { __typename: 'Book', title: string, bookFolder?: string | null, date: string, author: string, keywords: Array<string>, summary?: string | null, credits?: string | null, image?: string | null };

export type BookChapterPartsFragment = { __typename: 'BookChapter', title: string, bookFolder: string, section?: string | null, sectionFolder?: string | null, order?: number | null, date: string, body: any };

export type ArticleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArticleQuery = { __typename?: 'Query', article: { __typename: 'Article', id: string, title: string, date: string, author: string, type: string, tags: Array<string>, keywords: Array<string>, summary?: string | null, image?: string | null, audio?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArticleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticleFilter>;
}>;


export type ArticleConnectionQuery = { __typename?: 'Query', articleConnection: { __typename?: 'ArticleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArticleConnectionEdges', cursor: string, node?: { __typename: 'Article', id: string, title: string, date: string, author: string, type: string, tags: Array<string>, keywords: Array<string>, summary?: string | null, image?: string | null, audio?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SystematicTheologyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SystematicTheologyQuery = { __typename?: 'Query', systematicTheology: { __typename: 'SystematicTheology', id: string, title: string, subsection: string, subsectionFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SystematicTheologyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SystematicTheologyFilter>;
}>;


export type SystematicTheologyConnectionQuery = { __typename?: 'Query', systematicTheologyConnection: { __typename?: 'SystematicTheologyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SystematicTheologyConnectionEdges', cursor: string, node?: { __typename: 'SystematicTheology', id: string, title: string, subsection: string, subsectionFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ReformedTheologyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReformedTheologyQuery = { __typename?: 'Query', reformedTheology: { __typename: 'ReformedTheology', id: string, title: string, subsection: string, subsectionFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ReformedTheologyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReformedTheologyFilter>;
}>;


export type ReformedTheologyConnectionQuery = { __typename?: 'Query', reformedTheologyConnection: { __typename?: 'ReformedTheologyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReformedTheologyConnectionEdges', cursor: string, node?: { __typename: 'ReformedTheology', id: string, title: string, subsection: string, subsectionFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ChurchHistoryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ChurchHistoryQuery = { __typename?: 'Query', churchHistory: { __typename: 'ChurchHistory', id: string, title: string, subsection: string, subsectionFolder?: string | null, group?: string | null, groupFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ChurchHistoryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ChurchHistoryFilter>;
}>;


export type ChurchHistoryConnectionQuery = { __typename?: 'Query', churchHistoryConnection: { __typename?: 'ChurchHistoryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ChurchHistoryConnectionEdges', cursor: string, node?: { __typename: 'ChurchHistory', id: string, title: string, subsection: string, subsectionFolder?: string | null, group?: string | null, groupFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BookQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookQuery = { __typename?: 'Query', book: { __typename: 'Book', id: string, title: string, bookFolder?: string | null, date: string, author: string, keywords: Array<string>, summary?: string | null, credits?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BookConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
}>;


export type BookConnectionQuery = { __typename?: 'Query', bookConnection: { __typename?: 'BookConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookConnectionEdges', cursor: string, node?: { __typename: 'Book', id: string, title: string, bookFolder?: string | null, date: string, author: string, keywords: Array<string>, summary?: string | null, credits?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BookChapterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookChapterQuery = { __typename?: 'Query', bookChapter: { __typename: 'BookChapter', id: string, title: string, bookFolder: string, section?: string | null, sectionFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BookChapterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookChapterFilter>;
}>;


export type BookChapterConnectionQuery = { __typename?: 'Query', bookChapterConnection: { __typename?: 'BookChapterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookChapterConnectionEdges', cursor: string, node?: { __typename: 'BookChapter', id: string, title: string, bookFolder: string, section?: string | null, sectionFolder?: string | null, order?: number | null, date: string, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ArticlePartsFragmentDoc = gql`
    fragment ArticleParts on Article {
  __typename
  title
  date
  author
  type
  tags
  keywords
  summary
  image
  audio
  body
}
    `;
export const SystematicTheologyPartsFragmentDoc = gql`
    fragment SystematicTheologyParts on SystematicTheology {
  __typename
  title
  subsection
  subsectionFolder
  order
  date
  body
}
    `;
export const ReformedTheologyPartsFragmentDoc = gql`
    fragment ReformedTheologyParts on ReformedTheology {
  __typename
  title
  subsection
  subsectionFolder
  order
  date
  body
}
    `;
export const ChurchHistoryPartsFragmentDoc = gql`
    fragment ChurchHistoryParts on ChurchHistory {
  __typename
  title
  subsection
  subsectionFolder
  group
  groupFolder
  order
  date
  body
}
    `;
export const BookPartsFragmentDoc = gql`
    fragment BookParts on Book {
  __typename
  title
  bookFolder
  date
  author
  keywords
  summary
  credits
  image
}
    `;
export const BookChapterPartsFragmentDoc = gql`
    fragment BookChapterParts on BookChapter {
  __typename
  title
  bookFolder
  section
  sectionFolder
  order
  date
  body
}
    `;
export const ArticleDocument = gql`
    query article($relativePath: String!) {
  article(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArticleParts
  }
}
    ${ArticlePartsFragmentDoc}`;
export const ArticleConnectionDocument = gql`
    query articleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArticleFilter) {
  articleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArticleParts
      }
    }
  }
}
    ${ArticlePartsFragmentDoc}`;
export const SystematicTheologyDocument = gql`
    query systematicTheology($relativePath: String!) {
  systematicTheology(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SystematicTheologyParts
  }
}
    ${SystematicTheologyPartsFragmentDoc}`;
export const SystematicTheologyConnectionDocument = gql`
    query systematicTheologyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SystematicTheologyFilter) {
  systematicTheologyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SystematicTheologyParts
      }
    }
  }
}
    ${SystematicTheologyPartsFragmentDoc}`;
export const ReformedTheologyDocument = gql`
    query reformedTheology($relativePath: String!) {
  reformedTheology(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReformedTheologyParts
  }
}
    ${ReformedTheologyPartsFragmentDoc}`;
export const ReformedTheologyConnectionDocument = gql`
    query reformedTheologyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReformedTheologyFilter) {
  reformedTheologyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReformedTheologyParts
      }
    }
  }
}
    ${ReformedTheologyPartsFragmentDoc}`;
export const ChurchHistoryDocument = gql`
    query churchHistory($relativePath: String!) {
  churchHistory(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ChurchHistoryParts
  }
}
    ${ChurchHistoryPartsFragmentDoc}`;
export const ChurchHistoryConnectionDocument = gql`
    query churchHistoryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ChurchHistoryFilter) {
  churchHistoryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ChurchHistoryParts
      }
    }
  }
}
    ${ChurchHistoryPartsFragmentDoc}`;
export const BookDocument = gql`
    query book($relativePath: String!) {
  book(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookParts
  }
}
    ${BookPartsFragmentDoc}`;
export const BookConnectionDocument = gql`
    query bookConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookFilter) {
  bookConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookParts
      }
    }
  }
}
    ${BookPartsFragmentDoc}`;
export const BookChapterDocument = gql`
    query bookChapter($relativePath: String!) {
  bookChapter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookChapterParts
  }
}
    ${BookChapterPartsFragmentDoc}`;
export const BookChapterConnectionDocument = gql`
    query bookChapterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookChapterFilter) {
  bookChapterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookChapterParts
      }
    }
  }
}
    ${BookChapterPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      article(variables: ArticleQueryVariables, options?: C): Promise<{data: ArticleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleQueryVariables, query: string}> {
        return requester<{data: ArticleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleQueryVariables, query: string}, ArticleQueryVariables>(ArticleDocument, variables, options);
      },
    articleConnection(variables?: ArticleConnectionQueryVariables, options?: C): Promise<{data: ArticleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleConnectionQueryVariables, query: string}> {
        return requester<{data: ArticleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticleConnectionQueryVariables, query: string}, ArticleConnectionQueryVariables>(ArticleConnectionDocument, variables, options);
      },
    systematicTheology(variables: SystematicTheologyQueryVariables, options?: C): Promise<{data: SystematicTheologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SystematicTheologyQueryVariables, query: string}> {
        return requester<{data: SystematicTheologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SystematicTheologyQueryVariables, query: string}, SystematicTheologyQueryVariables>(SystematicTheologyDocument, variables, options);
      },
    systematicTheologyConnection(variables?: SystematicTheologyConnectionQueryVariables, options?: C): Promise<{data: SystematicTheologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SystematicTheologyConnectionQueryVariables, query: string}> {
        return requester<{data: SystematicTheologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SystematicTheologyConnectionQueryVariables, query: string}, SystematicTheologyConnectionQueryVariables>(SystematicTheologyConnectionDocument, variables, options);
      },
    reformedTheology(variables: ReformedTheologyQueryVariables, options?: C): Promise<{data: ReformedTheologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReformedTheologyQueryVariables, query: string}> {
        return requester<{data: ReformedTheologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReformedTheologyQueryVariables, query: string}, ReformedTheologyQueryVariables>(ReformedTheologyDocument, variables, options);
      },
    reformedTheologyConnection(variables?: ReformedTheologyConnectionQueryVariables, options?: C): Promise<{data: ReformedTheologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReformedTheologyConnectionQueryVariables, query: string}> {
        return requester<{data: ReformedTheologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReformedTheologyConnectionQueryVariables, query: string}, ReformedTheologyConnectionQueryVariables>(ReformedTheologyConnectionDocument, variables, options);
      },
    churchHistory(variables: ChurchHistoryQueryVariables, options?: C): Promise<{data: ChurchHistoryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChurchHistoryQueryVariables, query: string}> {
        return requester<{data: ChurchHistoryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChurchHistoryQueryVariables, query: string}, ChurchHistoryQueryVariables>(ChurchHistoryDocument, variables, options);
      },
    churchHistoryConnection(variables?: ChurchHistoryConnectionQueryVariables, options?: C): Promise<{data: ChurchHistoryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChurchHistoryConnectionQueryVariables, query: string}> {
        return requester<{data: ChurchHistoryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChurchHistoryConnectionQueryVariables, query: string}, ChurchHistoryConnectionQueryVariables>(ChurchHistoryConnectionDocument, variables, options);
      },
    book(variables: BookQueryVariables, options?: C): Promise<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}> {
        return requester<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}, BookQueryVariables>(BookDocument, variables, options);
      },
    bookConnection(variables?: BookConnectionQueryVariables, options?: C): Promise<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}> {
        return requester<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}, BookConnectionQueryVariables>(BookConnectionDocument, variables, options);
      },
    bookChapter(variables: BookChapterQueryVariables, options?: C): Promise<{data: BookChapterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookChapterQueryVariables, query: string}> {
        return requester<{data: BookChapterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookChapterQueryVariables, query: string}, BookChapterQueryVariables>(BookChapterDocument, variables, options);
      },
    bookChapterConnection(variables?: BookChapterConnectionQueryVariables, options?: C): Promise<{data: BookChapterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookChapterConnectionQueryVariables, query: string}> {
        return requester<{data: BookChapterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookChapterConnectionQueryVariables, query: string}, BookChapterConnectionQueryVariables>(BookChapterConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  